name: my_wheater_app
description: Zian WheaterApp
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  fl_location: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.3.0
  good_search_appbar: ^0.0.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mocktail: ^1.0.3
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
